### ISSUE TITLE
ACRE Module: Unit attributes broken.

### ISSUE THREAD

**Issue by thecogdoctor** [PiZZAD0X/UnitedOperationsFramework#16]
#### Description of issue

"Give 'X Type' Radio" in ACRE unit settings does not give the unit the selected radio.

#### Steps to reproduce

Add the steps needed to reproduce the issue. For example:

1.  UO Framework button in the editor
2.  Configure ACRE
3.  Configure ACRE settings
4. Enable ACRE Framework -> ☑️ 
5. Repeat steps 1 and 2, then select the faction you want to test with.
6. Specify a faction short range radio, long range radio and pack radio type.
5, Place a unit down in the editor
6. Select this unit and open the ACRE Options attribute.
7. Enable ACRE Unit Settings -> ☑️ 
8. Give "XYZ" Radio -> ☑️ 
9. Load mission into multiplayer or singleplayer (only tested on hosting atm)

#### Expected behaviour

Radios specified within faction attributes are suppoused to be given to playable units.

#### Additional context

Experienced on most recent commit to MacroRewrite.

**Comment by PiZZAD0X** [comment]
Check latest commit
